{% set name = "pyjanitor" %}
{% set version = "0.32.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyjanitor-devs/pyjanitor/archive/v{{ version }}.tar.gz
  sha256: 4ac136460ad177b7fe8805f7e21cb0fe1bc47567613be1e23068d7afafd295a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pandas-flavor
    - multipledispatch
    - natsort
    - pandas
    - pandas_flavor >=0.5
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - janitor
    - janitor.accessors

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
