{% set python_min = "3.11" %}
{% set name = "pyjanitor" %}
{% set version = "0.32.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyjanitor-devs/pyjanitor/archive/v{{ version }}.tar.gz
  sha256: f41f165a30885c531832806d16d839890dc0b246e75ca5a850e60946c761df4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - janitor-rs >=0.6.1,<0.7
    - python >={{ python_min }}
    - pandas-flavor >=0.8.1,<0.9
    - multipledispatch
    - natsort >=8.4.0,<9
    - pandas
    - pandas_flavor >=0.5
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - janitor
    - janitor.accessors

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
