{% set name = "pyjanitor" %}
{% set version = "0.27.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyjanitor-devs/pyjanitor/archive/v{{ version }}.tar.gz
  sha256: 3c348e830e63e5cefdcfa6e92b5d9dc1b3ae4e2c86683a1726a930343b9cb494

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - pandas-flavor
    - python >=3.6
    - multipledispatch
    - natsort
    - pandas
    - pandas_flavor >=0.5
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - janitor
    - janitor.accessors

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
