{% set name = "pyjanitor" %}
{% set version = "0.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyjanitor-devs/pyjanitor/archive/v0.23.1.tar.gz
  sha256: c15545117388cceab0b05f3e9bdbfad822dd71b2a7eb528132da05ff9c53ea5b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - multipledispatch
    - natsort
    - pandas
    - pandas_flavor >=0.5
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - janitor
    - janitor.accessors

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
